QBDI/QBDI

- examples/pyqbdi/coverage.py
- examples/pyqbdi/trace_sin.py
- include/QBDI/Callback.h
- src/Utility/Memory.cpp
- tools/QBDIPreload/src/darwin_preload.c
- tools/QBDIPreload/src/linux_preload.c
- tools/frida-qbdi.js
- tools/pyqbdi/pyqbdi.cpp
This PR also includes a (tricky) fix for getRemoteProcessMaps (which was broken on macOS).
> Add atexit and getCurrentProcessMaps support in pyQBDI

- docs/source/intro.rst
- docs/source/pyQBDI.rst
- docs/source/qbdi_preload.rst
This should explain issues like #27 and #33.
> Fix documentation issues regarding QBDI limitations

- README.rst
Added details about installing Command Line Tools, packages, etc.
> Improve compilation doc on macOS (related to issue #26)

- src/ExecBlock/ExecBlockManager.cpp
I made a mistake with indexes in the region cache implementation resulting in very rare region corruption. Elia confirmed this does indeed fixes it with his tests.
> Fix the cache region corruption problem

- include/QBDI/InstAnalysis.h
- src/ExecBlock/ExecBlockManager.cpp
- test/API/VMTest.cpp
This PR aims at fixing the issue #57 
I've "improved" regression tests for operand analysis to cover more corner cases (especially the broken ones in the issue).
> Fix implicit regs analysis

- examples/modules.c
- include/QBDI/Memory.h
- include/QBDI/Memory.hpp
- src/Utility/Memory.cpp
- src/Utility/Memory_linux.cpp
- src/Utility/Memory_macOS.cpp
- src/Utility/Memory_win.cpp
- tools/QBDIPreload/src/linux_preload.c
- tools/pyqbdi/pyqbdi.cpp
> Feature/process maps with full_path

- CMakeLists.txt
- cmake/config-android-ARM.sh
- cmake/config-android-X86.sh
- deps/gtest/android-X86/build.sh
- deps/llvm/build.py
- include/QBDI/Platform.h
- package/android_X86_docker_packager/Dockerfile
- package/android_X86_docker_packager/build.sh
- package/launch_docker_packager.sh
- src/ExecBlock/android-X86_Stub.s
- test/API/VMTest.cpp
- test/CMakeLists.txt
add support for android-X86 and package
Remove stack protection for a test method (test fail to the cmp of stack
protection)
> Add android-X86

- include/QBDI/InstAnalysis.h
- src/ExecBlock/Context.h
- src/ExecBlock/ExecBlockManager.cpp
- src/Patch/ARM/InstInfo_ARM.cpp
- src/Patch/InstInfo.h
- src/Patch/X86_64/InstInfo_X86_64.cpp
- test/API/VMTest.cpp
- test/QBDITest.cpp
Fix immediate size in InstAnalysis
> immediate Size and additionnal register in InstAnalysis

- CMakeLists.txt
- tools/frida-qbdi.js
- fix frida version to 0.7.1
- add a list of version to change when release
see #133
> Fix frida for next version

- docs/source/frida_bindings.rst
- tools/frida-qbdi.js
Check with https://qbdi.readthedocs.io/en/docs-frida/frida_bindings.html
> Correct frida docs

- tools/validation_runner/RunConfig.py
- tools/validation_runner/RunOrchestrator.py
- tools/validation_runner/RunResult.py
- tools/validation_runner/SQLite.py
- tools/validation_runner/TestResult.py
- tools/validation_runner/ValidationRunner.py
- tools/validator/darwin_validator.cpp
- tools/validator/instrumented.cpp
- tools/validator/instrumented.h
- tools/validator/linux_validator.cpp
- tools/validator/master.cpp
- tools/validator/master.h
- tools/validator/pipes.cpp
- tools/validator/pipes.h
- tools/validator/validatorengine.cpp
- tools/validator/validatorengine.h
This is a split of #131.
- Use unnamed pipe in validator and validator_runner
- check mismatch of memoryAccess
> Add memoryAccess check in validator

- README.rst
This fixes the broken documentation link :)
> Fix doc link

- examples/thedude.c
- examples/thedude.cpp
- include/QBDI/Platform.h
- src/ExecBlock/ExecBlockManager.cpp
- src/Patch/InstrRule.cpp
- src/Utility/System.cpp
- test/API/MemoryAccessTest_X86.cpp
- test/API/MemoryAccessTest_X86_64.cpp
- test/API/VMTest.cpp
- Fix regions cost overflow
- Fix compilation and bug with ASAN
> Fix regions cost overflow

- templates/qbdi_frida_template/FridaQBDI_sample.js
> Fix frida template

- src/Engine/Engine.cpp
- src/Patch/InstMetadata.h
- src/Patch/Patch.cpp
- src/Patch/Patch.h
- test/ExecBlock/CMakeLists.txt
- test/ExecBlock/ExecBlockManagerTest.cpp
- test/ExecBlock/ExecBlockTest.cpp
- test/ExecBlock/PatchEmpty.h
- test/ExecBlock/X86/CMakeLists.txt
- test/ExecBlock/X86/PatchEmptyX86.cpp
- test/ExecBlock/X86_64/CMakeLists.txt
- test/ExecBlock/X86_64/PatchEmptyX86_64.cpp
Patch must be associated with a valid MCInst
> fix Internal Patch

- src/Patch/Register.cpp
- src/Patch/Register.h
- src/Patch/X86_64/PatchRules_X86_64.cpp
- src/Patch/X86_64/Register_X86_64.cpp
- src/Utility/X86_64/InstAnalysis_X86_64.cpp
- test/API/X86/InstAnalysisTest_X86.cpp
- test/API/X86_64/InstAnalysisTest_X86_64.cpp
- test/Patch/X86/CMakeLists.txt
- test/Patch/X86/ComparedExecutor_X86.cpp
- test/Patch/X86/ComparedExecutor_X86.h
- test/Patch/X86/Instr_Test_X86.cpp
- test/Patch/X86/Patch_Test_X86.cpp
- test/Patch/X86_64/ComparedExecutor_X86_64.cpp
- test/Patch/X86_64/ComparedExecutor_X86_64.h
- Add PatchRule for `loop`, `loope` and `loopne`
- Fix llvm register used (add rcx in the register used by `loop*` instructions)
> Add support for loop|loope|loopne instructions

- tools/QBDIPreload/src/X86/linux_X86.c
- tools/QBDIPreload/src/X86_64/linux_X86_64.c
> Add new name of libc in QBDIPreload blacklist

- include/QBDI/VM.h
- include/QBDI/VM_C.h
- src/Engine/VM.cpp
- src/Engine/VM_C.cpp
- src/ExecBlock/ARM/linux-android_ARM.s
- src/ExecBlock/X86_64/windows-X86_64.asm
- src/Utility/AARCH64/CMakeLists.txt
- src/Utility/AARCH64/linux-android-AARCH64.s
- src/Utility/AARCH64/osx-AARCH64.s
- src/Utility/ARM/CMakeLists.txt
- src/Utility/ARM/ios_ARM.s
- src/Utility/ARM/linux-android_ARM.s
- src/Utility/CMakeLists.txt
- src/Utility/Memory.cpp
- src/Utility/StackSwitch.cpp
- src/Utility/StackSwitch.h
- src/Utility/X86_64/CMakeLists.txt
- src/Utility/X86_64/linux-X86.s
- src/Utility/X86_64/linux-X86_64.s
- src/Utility/X86_64/osx-X86.s
- src/Utility/X86_64/osx-X86_64.s
- src/Utility/X86_64/windows-X86.asm
- src/Utility/X86_64/windows-X86_64.asm
- test/API/VMTest.cpp
- tools/frida-qbdi.js
> Stack switch

- .github/workflows/python_osx.yml
- .github/workflows/python_windows.yml
- docker/ci_python_linux/build_whl.sh
- docker/python_linux_arm/images/build_docker_img.sh
- docker/python_linux_arm/whl_build.sh
- setup.cfg
- tools/pyqbdi/CMakeLists.txt
- tools/pyqbdi/binding/AARCH64/State_AARCH64.cpp
- tools/pyqbdi/binding/ARM/State_ARM.cpp
- tools/pyqbdi/binding/Callback.cpp
- tools/pyqbdi/binding/Memory.cpp
- tools/pyqbdi/binding/Range.cpp
- tools/pyqbdi/binding/X86/State_X86.cpp
- tools/pyqbdi/binding/X86_64/State_X86_64.cpp
> Add support for python 3.12

- tools/frida-qbdi.js
It's about the issue #251, and I've been using it with typescript for a few days.
Also, it's formatted by the VSCode's default formatter, I keep the changes because I didn't find any related rules in the repo.
> Add jsdoc for intellisense

- docs/source/index.rst
Thanks for working on this project! I'm just starting to investigate it, and I noticed this small typo in documentation.
> Fix documentation contents typo

- .github/workflows/python_linux.yml
- .github/workflows/python_osx.yml
- .github/workflows/python_windows.yml
- cmake/QBDIDependencies.cmake
- docker/ci_python_linux/Dockerfile
- docker/ci_python_linux/build_whl.sh
- docker/ci_python_linux/whl_build.sh
- docker/python_linux_arm/images/build_docker_img.sh
- docker/python_linux_arm/whl_build.sh
- docs/rtd_pyqbdi_artifact/setup.py
- setup.cfg
> PyQBDI for python 3.13

- .github/workflows/python.yml
- .github/workflows/python_linux.yml
- .github/workflows/python_osx.yml
- .github/workflows/python_windows.yml
- .readthedocs.yml
- README.rst
- cmake/QBDIDependencies.cmake
- docs/rtd_pyqbdi_artifact/setup.py
- setup.cfg
- setup.py
- tools/pyqbdi/CMakeLists.txt
Add auto push to Pypi when release
Fix compiled wheel in CI (compiled with the wrong version of Python)
> CI push to Pypi & Fix PyQBDI compilation

- templates/qbdi_frida_template/FridaQBDI_sample.js
- tools/frida-qbdi.js
~~WIP : doesn't work with last version of frida-compile. Need to be compiled with frida-compile@17.0.0~~ : work with frida-compile@19.0.4
> Update to frida 17
